# Generated by Django 5.1.1 on 2024-10-04 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaurio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('era', models.CharField(max_length=150)),
                ('dieta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paleontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('anos_experiencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Excavacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('dinosaurio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dinosaurios.dinosaurio')),
            ],
        ),
    ]
